# == In this configuration you setup AlchemyÂ´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: logo
  contents:
    - name: image
      type: EssencePicture
      validate:
        - presence: true
    - name: logo_text
      type: EssenceHtml
      validate:
        - presence: true

- name: teaser
  contents:
    - name: link
      type: EssenceLink
      validate:
        - presence: true
    - name: image
      type: EssencePicture
      validate:
        - presence: true
    - name: super_title
      type: EssenceText
      validate:
        - presence: true
    - name: title
      type: EssenceText
      validate:
        - presence: true
    - name: body
      type: EssenceRichtext
      validate:
        - presence: true

- name: topics
  contents:
    - name: title
      type: EssenceText
      validate:
      - presence: true
  available_contents:
    - name: topic
      type: EssenceText

- name: testimonial
  contents:
    - name: citee
      type: EssenceText
      validate:
        - presence: true
    - name: quote
      type: EssenceText
      validate:
        - presence: true

- name: contact_form
  contents:
    - name: mail_from
      type: EssenceText
      validate:
        - presence: true
        - format: email
    - name: mail_to
      type: EssenceText
      validate:
        - presence: true
        - format: email
    - name: subject
      type: EssenceText
      validate:
        - presence: true
    - name: success_page
      type: EssenceSelect
      validate:
        - presence: true

- name: static_page_header
  contents:
    - name: image
      type: EssencePicture
      validate:
        - presence: true
    - name: super_title
      type: EssenceText
      validate:
        - presence: true

- name: static_page
  contents:
    - name: title
      type: EssenceText
      validate:
        - presence: true
    - name: teaser
      type: EssenceRichtext
    - name: body
      type: EssenceRichtext
      validate:
        - presence: true


- name: address
  contents:
    - name: company_name
      type: EssenceText
      validate:
        - presence: true
    - name: name
      type: EssenceText
      validate:
        - presence: true
    - name: street
      type: EssenceText
      validate:
        - presence: true
    - name: place
      type: EssenceText
      validate:
        - presence: true
    - name: phone
      type: EssenceText
      validate:
        - presence: true
    - name: email
      type: EssenceText
      validate:
        - presence: true

- name: link
  contents:
    - name: link
      type: EssenceText
      settings:
        linkable: true

